spring:
  datasource:
    name: swapidb
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
logging:
  level:
    root: INFO
    com.github.marceloverdijk.swapi.labs: DEBUG
management:
  endpoints:
    jmx:
      enabled: false
    web:
      enabled: true
      expose: "*"
